export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';
export const POST_FETCH_MORE = "POST_FETCH_MORE";
export const FETCH_PENDING = 'FETCH_PENDING';
export const STICKY_FETCH_SUCCESS = 'STICKY_FETCH_SUCCESS';

export const POST_CHANGE_LAYOUT_SUCCESS = 'POST_CHANGE_LAYOUT_SUCCESS';
export const POST_RELATED_FETCH_SUCCESS = 'POST_RELATED_FETCH_SUCCESS';

export const TAG_ON_SELECT = 'TAG_ON_SELECT';
export const TAG_FETCH_SUCCESS = 'TAG_FETCH_SUCCESS';

export const CATEGORY_FETCH_SUCCESS = 'CATEGORY_FETCH_SUCCESS';
export const CATEGORY_ON_SELECT = 'CATEGORY_ON_SELECT';

export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS';
export const VIDEO_FETCH_MORE = 'VIDEO_FETCH_MORE';
export const PHOTO_FETCH_SUCCESS = 'PHOTO_FETCH_SUCCESS';
export const PHOTO_FETCH_MORE = 'PHOTO_FETCH_MORE';

export const FETCH_POST_BOOKMARK_SUCCESS = 'FETCH_POST_BOOKMARK_SUCCESS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const CLEAR_USER_SUCCESS = 'CLEAR_USER_SUCCESS';
export const FETCH_POST_BY_USER_SUCCESS = 'FETCH_POST_BY_USER_SUCCESS';
export const FETCH_POSTS_USER_MORE = 'FETCH_POSTS_USER_MORE';

export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS';
export const CATEGORY_SELECT_LAYOUT = 'CATEGORY_SELECT_LAYOUT';

export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';

export const INIT_POSTS = 'INIT_POSTS';
export const POST_TAG_FETCH_SUCCESS = 'POST_TAG_FETCH_SUCCESS'
export const POST_TAG_FETCH_MORE = 'POST_TAG_FETCH_MORE'

export const POST_ID_FETCH_SUCCESS = 'POST_ID_FETCH_SUCCESS'

// notification
export const INITIAL_NOTIFICATION = 'INITIAL_NOTIFICATION'
export const GET_TOKENS = 'GET_TOKENS'
export const GOT_TOKENS = 'GOT_TOKENS'

export const FINISH_INTRO = 'FINISH_INTRO'

export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_PARENT_CATEGORIES_PENDING = 'GET_PARENT_CATEGORIES_PENDING';
export const GET_PARENT_CATEGORIES_SUCCESS = 'GET_PARENT_CATEGORIES_SUCCESS';
export const GET_PARENT_CATEGORIES_FAIL = 'GET_PARENT_CATEGORIES_FAIL';

export const GET_SUB_CATEGORIES_PENDING = 'GET_SUB_CATEGORIES_PENDING';
export const GET_SUB_CATEGORIES_SUCCESS = 'GET_SUB_CATEGORIES_SUCCESS';
export const GET_SUB_CATEGORIES_FAIL = 'GET_SUB_CATEGORIES_FAIL';
